language: node_js
node_js:
  - '12'
install:
  - yarn --frozen-lockfile
script: yarn test
cache:
  directories:
    - node_modules
env:
  matrix:
    - CI=true TZ=Europe/Paris
notifications:
  email: false
